---
title: "Programa de Prevención y Control del Dengue | 2025"
format: 
  dashboard:
    nav-buttons: [twitter, github, facebook]
theme: custom.scss
---

```{r setup}
library(sf)
mapview::mapviewOptions(default = TRUE,
                        basemaps.color.shuffle = FALSE)
```


# [**Hotspots de Dengue**]{style="font-size:2pt"}

::: panel-tabset

### [**Jalpa**]{style="color:#990000"}

<html>
<head>
```{=html}
<style>
body {
  margin: 0px;
  width: auto; 
  height: auto;
}

.wrapper {
    display: grid;
    grid-gap: 1px;
    grid-template-columns: 225px 225px 225px 410px;
    grid-template-rows: 95px 95px 95px 130px;
    background-color: #772953;
    color: "#772953";
  }

  .box {
    background-color: #772953;
    color: "#772953";
    border-radius: 1px;
    padding: 2px;
    font-size: 100%;
  }

  .a {
    grid-column: 1 / 4;
    grid-row: 1 / 4;
  }
  .b {
    grid-column: 4 ;
    grid-row: 1 / 3;
  }
  .c {
    grid-column: 4 ;
    grid-row: 3 / 5 ;
  }
  .d {
    grid-column: 3;
    grid-row: 4;
  }
  .e {
    grid-column: 2;
    grid-row: 4;
  }
  .f {
    grid-column: 1;
    grid-row: 4;
  }
</style>
```
</head>
<body>
::: wrapper
::: {.box .a}
```{r hotspots_dengue_Jalpa}
loc <- rgeomex::extract_locality(cve_edo = "32", 
                                 locality = "Jalpa")

# Step 2. Extract the hotspots ####
hotspots <- hotspotsdata::den_hotspots[loc, ]
mapview::mapview(hotspots,
                 zcol = "intensity_gi",
                 layer.name = "Intensidad",
                 label = FALSE,
                 color = "white",
                 lwd = 0.5, 
                 col.regions =  rcartocolor::carto_pal(n = max(hotspots$intensity_gi), 
                                                       name = "OrYel"))


```
:::

::: {.box .b}
```{r forest_plot_jalpa, dpi = 300, fig.align = "center", out.height='100%', out.width = '100%',fig.show = "hold"}
 
# Logistic Regression
hotspots <- hotspots |>
    dplyr::mutate(DENV_2008_2010 = DENV_2008 + DENV_2009 + DENV_2010) |>
    plyr::mutate(DENV_2011_2014 = DENV_2011 + DENV_2012 + DENV_2013 + DENV_2014) |>
    dplyr::mutate(DENV_2015_2017 = DENV_2015 +  DENV_2016 + DENV_2017) |>
    dplyr::mutate(DENV_2018_2019 = DENV_2018 +  DENV_2019) |>
    dplyr::mutate(DENV_2020_2021 = DENV_2020 +  DENV_2021) |>
    dplyr::mutate(DENV_2022_2023 = DENV_2022 +  DENV_2023) 


# Logistic Regression
glm.fit <- glm(hotspots_gi ~ DENV_2008_2010 + DENV_2011_2014 +
                   DENV_2015_2017 + DENV_2018_2019 +
                   DENV_2020_2021 + DENV_2022_2023,
               data = hotspots, 
               family = binomial)

ggstats::ggcoef_table(glm.fit,
                      significance_labels = c("Significativo", 
                                              "No singificativo"),
                      stripped_rows = TRUE,
                      exponentiate = TRUE) 
```
:::

::: {.box .c}
```{r power_law_plot_jalpa,dpi = 300, warning=FALSE, fig.align = "center", out.width = '100%',out.height='100%',fig.show = "hold"}
# Step 7. make the function por calculate the cumulative ####
funcumsum <- function(x){
    x$cumulative_n <- cumsum(x$n_cases)
    x$perc_cumsum_n <- round((cumsum(x$n_cases)/sum(x$n_cases))*100, digits = 1)
    #x$cumulative_ha <- cumsum(x$ha)
    #x$perc_cumsum_ha <- round((cumsum(x$ha)/sum(x$ha))*100, digits = 1)
    x$id <- 1
    x$id_cumsum <- cumsum(x$id)
    x$id_perc_cum <- round((cumsum(x$id)/nrow(x))*100, digits = 1)
    x
}
# step 8.
data_pareto <- hotspots   |>
    # sf::st_drop_geometry()  |>
    # dplyr::mutate(n_cases = rowSums(dplyr::select(., dplyr::starts_with("DENV"))),
    #              loc = "locality")
    #dplyr::mutate(n_cases = rowSums(dplyr::across(DENV_2008:DENV_2021)),
    #              loc = "locality")  |>
    dplyr::mutate(n_cases = rowSums(dplyr::across(dplyr::starts_with("DENV"))),
                  loc = "locality") |>
    
    dplyr::select(loc, n_cases, hotspots_gi)  |>
    dplyr::arrange(loc, desc(hotspots_gi), desc(n_cases))  |>
    dplyr::group_by(loc)  |>
    tidyr::nest()  |>
    dplyr::mutate(pareto_cases = purrr::map(data,
                                            funcumsum))  |>
    dplyr::select(-data)  |>
    tidyr::unnest(cols = c(pareto_cases))

# step 4. visualization of pareto rules 
plotly::ggplotly(denhotspots::power_law_plot(x = data_pareto))  |> plotly::layout(showlegend = FALSE)

```
:::

::: {.box .d}
```{r gauge_blocks_jalpa,fig.align = "center", out.height='100%', out.width = '100%', fig.width= 1.5, fig.height=1}
y_hot <- hotspots |> dplyr::filter(hotspots_gi == 1)
centroid <- rgeomex::blocks_ine20_mx_centroid |>
  sf::st_as_sf(coords = c("x", "y"), crs = 4326)
b_loc <- centroid[hotspots, ]
b_hot <- b_loc[y_hot, ]
flexdashboard::gauge(round((nrow(b_hot)/nrow(b_loc))*100, digits = 1),
                     min = 0, max = 100, 
                     symbol = '%', 
                     label = "Manzanas",
                     flexdashboard::gaugeSectors(success = c(0, 30), 
                                                 warning = c(31, 50), 
                                                 danger = c(51, 100),
                                                 colors = c("#11BB33", #"#63C1A0", 
                                                            "#FC8427",
                                                            "#E01A59")))
```
:::

::: {.box .e}
```{r gauge_AGEB_jalpa, fig.align = "center", out.height='100%', out.width = '100%'}

y <- hotspots  |>
    sf::st_drop_geometry() |>
     dplyr::mutate(n_cases = rowSums(dplyr::across(dplyr::starts_with("DENV"))),
                  loc = "locality") |>
    dplyr::select(loc, n_cases, hotspots_gi) 
y_hot <- y |>dplyr::filter(hotspots_gi == 1)
  
flexdashboard::gauge(round((nrow(y_hot)/nrow(y))*100, digits = 1),
      min = 0, max = 100, 
      symbol = '%', 
      label = "AGEBs",
      flexdashboard::gaugeSectors(success = c(0, 30), 
                                  warning = c(31, 50), 
                                  danger = c(51, 100),
                                  colors = c("#11BB33",
                                             "#FC8427",
                                             "#E01A59")))
```
:::

::: {.box .f}
```{r gauge_jalpa, out.height='90%', out.width = '90%', fig.align = "center"}

y <- hotspots  |>
    sf::st_drop_geometry() |>
      dplyr::mutate(n_cases = rowSums(dplyr::across(dplyr::starts_with("DENV"))),
                  loc = "locality") |>
    dplyr::select(loc, n_cases, hotspots_gi) 
y_hot <- y |>dplyr::filter(hotspots_gi == 1)

flexdashboard::gauge(round((sum(y_hot$n_cases)/sum(y$n_cases))*100, digits = 1),
      min = 0, max = 100, 
      symbol = '%', 
      label = "Casos de Dengue",
      flexdashboard::gaugeSectors(success = c(11, 100), 
                                  warning = c(6, 10), 
                                  danger = c(0, 5),
                                  colors = c("#11BB33", 
                                             "#FC8427",
                                             "#E01A59")))
```
:::
:::
</body>
</html>



:::

# [**Hotspots de Vector**]{style="font-size:2pt"}

::: panel-tabset


### [**Jalpa**]{style="color:#990000"}
```{r vector_jalpa, dpi = 300, warning=FALSE, message=FALSE}
deneggs::map_eggs_hotspots(betas = denmex::eggs_betas_32_zacatecas |>
                               dplyr::filter(year >= 2016),
                           locality = "Jalpa",
                           cve_edo = "32",
                           palette = rcartocolor::carto_pal,
                           name = "SunsetDark",
                           static_map = FALSE)
```

### [**Apozol**]{style="color:#990000"}
```{r vector_apozol, dpi = 300, warning=FALSE, message=FALSE}
deneggs::map_eggs_hotspots(betas = denmex::eggs_betas_32_zacatecas |>
                               dplyr::filter(year >= 2016),
                           locality = "Apozol",
                           cve_edo = "32",
                           palette = rcartocolor::carto_pal,
                           name = "SunsetDark",
                           static_map = FALSE)
```

### [**Jichipila**]{style="color:#990000"}
```{r vector_jichipila, dpi = 300, warning=FALSE, message=FALSE}
deneggs::map_eggs_hotspots(betas = denmex::eggs_betas_32_zacatecas |>
                               dplyr::filter(year >= 2016),
                           locality = "Jichipila",
                           cve_edo = "32",
                           palette = rcartocolor::carto_pal,
                           name = "SunsetDark",
                           static_map = FALSE)
```

### [**Moyahua**]{style="color:#990000"}
```{r vector_moyahua, dpi = 300, warning=FALSE, message=FALSE}
deneggs::map_eggs_hotspots(betas = denmex::eggs_betas_32_zacatecas |>
                               dplyr::filter(year >= 2016),
                           locality = "Moyahua de Estrada",
                           cve_edo = "32",
                           palette = rcartocolor::carto_pal,
                           name = "SunsetDark",
                           static_map = FALSE)
```

### [**Tabasco**]{style="color:#990000"}
```{r vector_tabasco, dpi = 300, warning=FALSE, message=FALSE}
deneggs::map_eggs_hotspots(betas = denmex::eggs_betas_32_zacatecas |>
                               dplyr::filter(year >= 2016),
                           locality = "Tabasco",
                           cve_edo = "32",
                           palette = rcartocolor::carto_pal,
                           name = "SunsetDark",
                           static_map = FALSE)
```

### [**Tlaltenango**]{style="color:#990000"}
```{r vector_tlaltenango, dpi = 300, warning=FALSE, message=FALSE}
deneggs::map_eggs_hotspots(betas = denmex::eggs_betas_32_zacatecas |>
                               dplyr::filter(year >= 2016),
                           locality = "Tlaltenango de Sanchez Roman",
                           cve_edo = "32",
                           palette = rcartocolor::carto_pal,
                           name = "SunsetDark",
                           static_map = FALSE)
```


:::


# [**Escenarios Epidemiológicos**]{style="font-size:2pt"}

::: panel-tabset
### [**Jalpa**]{style="color:#990000"}
```{r risk_ageb_jalpa}
denhotspots::risk_ageb(betas = denmex::eggs_betas_32_zacatecas,
                       hotspots = denmex::den_hotspots,
                       intensity_perc = 25,
                       locality = "Jalpa",
                       cve_edo = "32") |>
    denhotspots::map_risk(staticmap = FALSE)

```


:::



